CREATE TABLE people
(
    person_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullName    varchar(100) UNIQUE,
    yearOfBirth int check ( yearOfBirth > 1900 )
);

CREATE TABLE books
(
    book_id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id     int REFERENCES people (person_id),
    name          varchar(100),
    author        varchar(100),
    yearOfWriting int
);